/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun Jan 10 18:32:48 2010"
#define BUILD_TIME (1263144768L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x001feeccUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x44219264UL
#define VERSION_SANITY2 0xc0d28978UL

#define VERSION_STRING "0.0.7E7F3"
#define VERSION_ID \
 "Unix SlashEM Version 0.0.7E7F3 - last build Sun Jan 10 18:32:48 2010."
